[package]
name = "todo_list"
version = "1.0.0"
edition = "2021"

[dependencies]
rusqlite = "0.29.0"
chrono = "0.4"
clap = { version = "4.2", features = ["derive"]}
rand ="^0.8.0"
unicode-segmentation = "1.10"
